version: '3.8'

services: 
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=cumbia
      - POSTGRES_USER=cumbia
      - POSTGRES_PASSWORD=xDDncS9a6Gb4zU
    volumes: 
      - pgdata:/var/lib/posgresql/data
  web:
    build: .
    volumes: 
      - /var/cache/cumbia/static:/code/staticfiles
      - /var/opt/cumbia/media:/code/media
    ports: 
      - "8000:8000"
    depends_on: 
      - db

volumes: 
  pgdata: