version: '3.8'

services: 
  db:
    image: postgres
    environment: 
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes: 
      - pgdata:/var/lib/posgresql/data
  web:
    build: .
    volumes: 
      - static_volume:/code/staticfiles
      - ./media:/code/media
    expose: 
      - 8000
    depends_on: 
      - db
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment: 
      - CERTBOT_EMAIL
      - STAGING
      - DHPARAM_SIZE
      - RSA_KEY_SIZE
      - RENEWAL_INTERVAL
      - DEBUG
    env_file:
      - ./nginx/nginx-certbot.env
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - static_volume:/code/staticfiles
      - ./media:/code/media
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d

volumes: 
  pgdata:
  static_volume:
  nginx_secrets: