version: '3.8'

services: 
  db:
    image: postgres
    environment: 
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes: 
      - pgdata:/var/lib/posgresql/data
  web:
    build: .
    volumes: 
      - static_volume:/code/staticfiles
      - /var/opt/app/media:/var/opt/app/media
    ports: 
      - 8000:8000
    depends_on: 
      - db
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment: 
      - CERTBOT_EMAIL=zetoichi.dev@protonmail.com
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - static_volume:/code/staticfiles
      - /var/opt/app/media:/var/opt/app/media
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d

volumes: 
  pgdata:
  static_volume:
  nginx_secrets: