# Generated by Django 3.2.2 on 2021-05-11 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('display_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Display')),
                ('bio', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PicSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.photographer')),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='pics', verbose_name='Image')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('client', models.CharField(blank=True, default='', max_length=250, verbose_name='Client')),
                ('agency', models.CharField(blank=True, default='', max_length=250, verbose_name='Agency')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('picset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='portfolio.picset')),
            ],
        ),
    ]
