# Generated by Django 3.2.2 on 2021-05-11 21:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_picset_pic_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='photographer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographer',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='Orden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pic',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='portfolio.photographer'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
