# Generated by Django 3.2.2 on 2021-05-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210511_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photographer',
            options={'ordering': ['display_order'], 'verbose_name': 'Photographer', 'verbose_name_plural': 'Photographers'},
        ),
        migrations.AlterModelOptions(
            name='pic',
            options={'ordering': ['display_order'], 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.RemoveField(
            model_name='pic',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='client',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='title',
        ),
        migrations.AddField(
            model_name='pic',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='pic',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
    ]
