# Generated by Django 3.2.3 on 2021-05-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210518_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='photographer',
        ),
    ]
