# Generated by Django 3.2.3 on 2021-05-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_pic_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='pics',
            field=models.ManyToManyField(blank=True, to='portfolio.Pic', verbose_name='Fotos'),
        ),
    ]
