# Generated by Django 3.2.3 on 2021-05-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_photographer_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Main'),
        ),
    ]
