# Generated by Django 3.2.3 on 2021-06-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210603_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Mostrar'),
        ),
    ]
