# Generated by Django 3.2.4 on 2021-06-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_photographer_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='landscape',
            field=models.BooleanField(default=False, verbose_name='Main'),
        ),
    ]
