# Generated by Django 3.2.3 on 2022-04-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_pic_landscape'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='country',
            field=models.CharField(choices=[(1, 'Argentina'), (2, 'Chile')], default='Argentina', max_length=100, verbose_name='País'),
        ),
    ]
